
server {
  listen 8084 ssl;
  http2 on;

  server_name web.tythac.com.vn;

  ssl_certificate     /etc/letsencrypt/live/web.tythac.com.vn/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/web.tythac.com.vn/privkey.pem;

  error_page 497 =301 https://web.tythac.com.vn:8084$request_uri;
  
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/v1/ {
    proxy_pass http://warehouse-web-api:3084/api/v1/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_buffering off;
  }
}
